steps:
- name: 'golang:1.11.1-stretch'
  entrypoint: 'go'
  args: ['build', '.']
  env: ['GO111MODULE=on']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/toykvstore:$REVISION_ID', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/toykvstore:$REVISION_ID', '.' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment/toykvstore'
  - 'toykvstore=gcr.io/$PROJECT_ID/toykvstore:$REVISION_ID'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=your-first-cluster-1'
images:
- 'gcr.io/$PROJECT_ID/toykvstore'


