steps:
- name: 'gcr.io/cloud-builders/go'
  args: [ 'build' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/toykvstore', '.' ]
images:
- 'gcr.io/$PROJECT_ID/toykvstore'


